# -*- coding: utf-8 -*-
"""MS Azure Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15hfFPwKymGmNsf2JZyTxgPo8GbLZ2wPy
"""

pip install azure.cosmos

pip install azure.storage.blob

import pandas as pd
from azure.cosmos import exceptions, CosmosClient
from azure.storage.blob import BlobServiceClient
import io
from azure.cosmos.partition_key import PartitionKey

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px


import warnings
import uuid
warnings.filterwarnings("ignore")

df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/TIP /BigBasket Products.csv")
df.head()

df.info()

df.shape

df.rename(columns = {'index':'id'}, inplace = True)
df.info()

df['id'] = df['id'].astype(str)

print('category values')
df.category.value_counts()

print('subcategory values')
df.sub_category.value_counts()

df.isnull().sum()

#Mean of ratings
print('Mean Value')
rating_mean = df.rating.mean()
rating_mean

#Median of ratings
print('Median Value')
rating_median = df.rating.median()
rating_median

#filling the rating null values by mean rating
df.rating.fillna(value=rating_mean,inplace=True)

df.dropna(inplace=True)

df.isnull().sum()

print(f'Number of Brands is',df["brand"].nunique())
print(f'Number of Categories is',df["category"].nunique())
print(f'Number of Sub-Categories is',df["sub_category"].nunique())
print(f'Number of Products is', df["product"].nunique())
print(f'Number of Types is', df["type"].nunique())

sns.histplot(df.rating,kde=True)

df["discount"] = (df["market_price"] - df["sale_price"]) / df["market_price"] * 100
df.tail()

discount_data = df[df['discount'] == True]
discount_data

fig = plt.figure(figsize=(20,10))

sns.kdeplot(discount_data['rating'], shade=True, label='Discounted Products')
sns.kdeplot(df['rating'], shade=True, label='All Products')

plt.xlabel("Ratings", fontsize=15, weight='semibold')
plt.ylabel("Density", fontsize=15, weight='semibold')
plt.title("Relative distribution of all products with discounted products", fontsize=15, weight='semibold')

handles, labels = plt.gca().get_legend_handles_labels()
plt.legend(handles, labels, fontsize=12)

sns.pairplot(df,vars=['rating','sale_price','market_price'],hue='rating')

# printing top subcategories with 5.0 rating for each category
category_list = df['category'].value_counts().index.tolist()
fig, axes = plt.subplots(3, 3, figsize=(25,20))
for i in range(9):
    order = df['sub_category'].loc[df['category'] == category_list[i]].value_counts().index
    sns.countplot(ax=axes[i//3][i%3], x='sub_category', data=df.loc[df['category'] == category_list[i]], palette='GnBu', order=order)
    fig.subplots_adjust(hspace=.8)
    axes[i//3][i%3].set_title(f'Top sub-categories of {category_list[i]}: Rating 5.0')
    axes[i//3][i%3].set_xticklabels(order.tolist(), rotation = 45)

blob_connection_string = 'DefaultEndpointsProtocol=https;AccountName=inven;AccountKey=uxM4LqtpG4MZ+aUCeolmGsiWXgW2bD71Y1CeYW5a/HZkc+2rF2zotVq0xCYRTIxFkz5eH32/TxEv+ASt1GU15w==;EndpointSuffix=core.windows.net'
blob_service_client = BlobServiceClient.from_connection_string(blob_connection_string)
container_client = blob_service_client.get_container_client('inventory')

container_client.create_container()
blob_client = container_client.get_blob_client('inventory_data.csv')
blob_client.upload_blob(data=df.to_csv(index=False), overwrite=True)

blob_data = blob_client.download_blob()
blob_data_text = blob_data.content_as_text()
blob_inventory_data = pd.read_csv(io.StringIO(blob_data_text))

blob_inventory_data.head(5)

cosmos_endpoint = 'https://inven.documents.azure.com:443/'
cosmos_key = 'AOc9Bzg8cwg9b3XEFKjX9OWmdX6Pu2EfrosjnD50s0GWyXHkJaeZWKDaxV7vkybpL9tOs4pTqKbFACDbg7eabw=='
cosmos_client = CosmosClient(cosmos_endpoint, cosmos_key)

database_name = 'InventoryDB1'
container_name = 'InventoryContainer'
database = cosmos_client.create_database_if_not_exists(database_name)
container = database.create_container_if_not_exists(
    id=container_name,
    partition_key='/product',
    offer_throughput=400
)

df.head(1).to_dict

for _, row in df.iterrows():
    # item['id'] = str(uuid.uuid4())
    container.create_item(row.to_dict())

query = "SELECT * FROM c WHERE c.rating >= 4.0"
cosmos_results = list(container.query_items(query, enable_cross_partition_query=True))

cosmos_results

search_keyword = input('Enter your text : ')
filtered_blob_df = df[df['product'].str.contains(search_keyword, case=False)]

database = cosmos_client.get_database_client(database_name)
container = database.get_container_client(container_name)
query = f"SELECT * FROM c WHERE CONTAINS(c.product, '{search_keyword}')"
filtered_cosmos_results = list(container.query_items(query, enable_cross_partition_query=True))
filtered_cosmos_results

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Create a TF-IDF vectorizer
vectorizer = TfidfVectorizer(stop_words='english')

# Fit and transform the 'description' column
tfidf_matrix = vectorizer.fit_transform(df['description'].values.astype('U'))

def recommend_product(input_text):
    # Transform the input text using the vectorizer
    input_vector = vectorizer.transform([input_text])

    # Calculate the cosine similarity between input and dataset
    similarities = cosine_similarity(input_vector, tfidf_matrix)

    # Get the index of the most similar product
    most_similar_index = similarities.argmax()

    # Return the details of the most similar product
    most_similar_product = df.iloc[most_similar_index]
    return most_similar_product

# Test the function
user_input = input("Enter your text: ")
recommended_product = recommend_product(user_input)
print("Recommended Product:")
print("Name:", recommended_product['product'])
print("Brand:", recommended_product['brand'])
print("Category:", recommended_product['category'])

def recommend_products(input_text, num_recommendations=5):
    # Transform the input text using the vectorizer
    input_vector = vectorizer.transform([input_text])

    # Calculate the cosine similarity between input and dataset
    similarities = cosine_similarity(input_vector, tfidf_matrix)

    # Get the indices of the top N most similar products
    #The argsort function is used to get the indices of the top num_recommendations most similar products.
    top_indices = similarities.argsort()[0][-num_recommendations:][::-1]

    # Return the details of the top N most similar products
    top_products = df.iloc[top_indices]
    return top_products

# Test the function
user_input = input("Enter your text: ")
recommended_products = recommend_products(user_input)
print("Recommended Products:")
for index, product in recommended_products.iterrows():
    print("Name:", product['product'])
    print("Brand:", product['brand'])
    print("Category:", product['category'])
    print("-----------------------------")

from sklearn.linear_model import LinearRegression
X = df[['rating']]  # Feature: rating
y = df['sale_price']  # Target variable: saleprice

model = LinearRegression()
model.fit(X, y)

results_df = pd.DataFrame({
    'Rating': X['rating'],
    'Actual Sale Price': y,
    'Predicted Sale Price': model.predict(X)
})

print("Demand Forecasting Results:")
print(results_df)

plt.scatter(X, y, color='blue', label='Actual Data')
plt.plot(X, model.predict(X), color='red', label='Demand Forecast')
plt.xlabel('Rating')
plt.ylabel('Sale Price')
plt.title('Demand Forecasting')
plt.legend()
plt.show()

